services:
  ros2:
    build: .
    image: robot:latest
    container_name: ros2
    volumes:
      - ${PWD}:/home
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${XAUTHORITY}:${XAUTHORITY}
    working_dir: /home
    environment:
      - DISPLAY=${DISPLAY}
      - WAYLAND_DISPLAY=${WAYLAND_DISPLAY}
      - QT_QPA_PLATFORM=xcb
    stdin_open: true
    tty: true
    privileged: true
    devices:
      - /dev/video0:/dev/video0
    command: bash && pwd && colcon build